[package]
name = "lesson_10"
version = "0.1.0"
edition = "2021"

# See more keys and their deinitions at https://doc.rust-lang.org/cargo/reerence/maniest.html

[dependencies]
gnuplot = "0.0.39"
float-cmp = "0.9.0"
num = "0.4.1"
symphonia = "0.5.3"
num-traits = "0.2.17"
cpal = "0.15.2"